### PR TITLE
fix daemon restore

### PR DESCRIPTION
**Pull request by Crazykev**
1. add saveSandbox() to save runv sandbox persistence info.
2. implement some workflow in save/restore pod data.
3. fix some bugs.

For now, this PR could only support not running pod restore, others will be fixed in next PR in runv/hyperd.

### CODE REVIEW

**Comment by laijs** [comment]
it seems one of the pod (ID: "busybox") was failed to be removed without any notification, but the next creations of pods failed.

**Comment by Crazykev** [comment]
Just notice that removing pod data from db is also not implement yet, so those test pods(including  ID:"busybox") is restored when hyperd start again. I guess this is the reason that when running  integration test the second time, many cases will fail.

**Comment by laijs** [comment]
you could remove all pods at the end of every test

**Comment by Crazykev** [comment]
@laijs I've tried to add removing pod/container from daemondb, it should work now.

**Comment by laijs** [comment]
LGTM

**Pull request merged**
