### PR TITLE
try fix jenkins build

### PR DESCRIPTION
**Pull request by gnawux**
Signed-off-by: Wang Xu <gnawux@gmail.com>

### CODE REVIEW

**Comment by gnawux** [comment]
retest this please

**Comment by gnawux** [comment]
retest this please

**Comment by laijs** [comment]
the default hykins is not removed yet

**Comment by gnawux** [comment]
looks like a display issue, only run once, but 2 items show here.

**Comment by gnawux** [comment]
Passed, cool!

**Comment by gnawux** [comment]
an  commit for debug jenkins, **do not merge it**

**Comment by gnawux** [comment]
retest this please

**Comment by gnawux** [comment]
OK, merge this if build success

**Comment by Jimmy-Xu** [comment]
retest this please

**Comment by gnawux** [comment]
retest this please

**Comment by gnawux** [comment]
retest this please

**Comment by Jimmy-Xu** [comment]
retest this please, hykins

**Comment by gnawux** [comment]
PASS

This PR only affect the test environment, merge it.

**Pull request merged**
