### PR TITLE
parse image volumes before creating volumes

### PR DESCRIPTION
**Pull request by bergwolf**
If container image has defined volumes, we need to create them.

w/o this, mysql will fail to start because hyperd cannot find volumes defined in image.

### CODE REVIEW

**Comment by gnawux** [comment]
found a comment:

```
 		// configEtcHosts should be called later than parse volumes, guarantee the file is not described in container
 		c.configEtcHosts()
```

Then, who moved `parseVolumes()`

**Comment by gnawux** [comment]
@gao-feng in #490 moved the `parseVolume()`, therefore, I suggest you ( @bergwolf  ) check the case fixed by #490

**Comment by bergwolf** [comment]
@gnawux thx! I've update the PR to cover #490 case.
```
[hypervsock@~]$sudo hyperctl run -p mysql.pod
POD id is pod-JPRHxqCRNZ
Time to run a POD is 9159 ms

[hypervsock@~]$sudo hyperctl exec pod-JPRHxqCRNZ df
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/sdb        10474496 446272  10028224   5% /
devtmpfs          119900      0    119900   0% /dev
tmpfs             124748      0    124748   0% /dev/shm
rootfs            119888  20248     99640  17% /lib/modules/4.9.11-hyper
/dev/sda         1998672 130424   1747008   7% /var/lib/mysql
share_dir           1024      4      1020   1% /etc/hosts

[hypervsock@~]$sudo hyperctl exec pod-JPRHxqCRNZ cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by bergwolf** [comment]
retest this please, @hykins

**Comment by gnawux** [comment]
retest this please, hykins

**Comment by gnawux** [comment]
retest this please, hykins

**Comment by gnawux** [comment]
retest this please, h

**Pull request merged**
