### PR TITLE
Add TTYResize grpc API

### PR DESCRIPTION
**Pull request by Crazykev**

### CODE REVIEW

**Comment by Crazykev** [comment]
@Jimmy-Xu Does hykins have a timeout, this test have run over 2 hours.

**Comment by Crazykev** [comment]
retest this please @hykins

**Comment by feiskyer** [comment]
@Crazykev  Conflicts, please re-generate the protobuf.

**Comment by Crazykev** [comment]
@feiskyer fixed and CI passed.

**Comment by feiskyer** [comment]
LGTM. Thanks.

**Pull request merged**
