### PR TITLE
Ignore vmlogd binary in git repo

### PR DESCRIPTION
**Pull request by Crazykev**
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

### CODE REVIEW

**Comment by gnawux** [comment]
LGTM

**Comment by Crazykev** [comment]
retest this please, @hykins

**Comment by laijs** [comment]
retest this please, @hykins

**Comment by gnawux** [comment]
retest this please, hykins

**Comment by Crazykev** [comment]
merge this based on review an CI.

**Pull request merged**
