### PR TITLE
add creation time to list

### PR DESCRIPTION
**Pull request by jgillich**
Adds a created column, similar to `docker ps`:
```
./hyperctl list container
Container ID                                                       Name                      POD ID              Status              Created
6b8a3340b0b79e3036965548e172cd15ef67e67e8406cd13555fb646b774b352   agitated_booth            pod-thTGDAjTOW      running             1 hour ago
7f3dd478a82b2d33bec0096cfc89f73887dea5bdb4a7246cf251e9bd9d98af43   happy_mirzakhani          pod-HTDTlyUqhe      running             1 hour ago
8f9e54f49b06c2123718a627751fa35bdef99dffd0752c4559a910b761c6db1e   big_gates                 pod-qFMOiURfmo      pending             4 days ago
```

### CODE REVIEW

**Comment by jgillich** [comment]
Totally forgot to update godeps, but I don't know what's going on here:
```
 $ godep save
godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.
godep: WARNING: Go version (go1.7) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
godep: WARNING: Recorded major go version (go1.5) and in-use major go version (go1.7) differ.
godep: To record current major go version run `godep update -goversion`.
godep: Package (github.com/docker/docker/pkg/mflag) not found

```

**Comment by gnawux** [comment]
@jgillich We notice the docker changes as well. 

Currently we are busying in fixing the issues ( #462  ) introduced in the recent refactor, and will move Godeps to `vendor/` and fix the  godep issues.

Could you add the dep with some manually work, or wait for a while?

Thanks very much for your contribution.

**Comment by jgillich** [comment]
Have you considered using [glide](https://github.com/Masterminds/glide)? I'm in no rush with this PR, but I could maybe help with moving to `vendor/`.

**Comment by gnawux** [comment]
Thanks @jgillich , I think @laijs may like to do this because he has done the same thing on hyperhq/runv weeks ago.

**Comment by Jimmy-Xu** [comment]
Can one of the admins verify this patch?

**Comment by Jimmy-Xu** [comment]
Can one of the admins verify this patch?

**Comment by Jimmy-Xu** [comment]
retest this please

**Comment by Jimmy-Xu** [comment]
retest this please

**Comment by Jimmy-Xu** [comment]
retest this please

**Comment by jgillich** [comment]
What do you mean? This is broken because the Godeps need updating.

**Comment by Jimmy-Xu** [comment]
@jgillich "retest this please" is a statement for Jenkins. Please ignore.

**Comment by jgillich** [comment]
Ah cool :)

**Comment by gnawux** [comment]
@jgillich The `godeps` has been moved to `vendor/`, update is welcome.

**Comment by gnawux** [comment]
open too long time. re-open it if there is an update

**Pull request closed without merging**
