### PR TITLE
cleanup: move src for bin files to cmd/ subdir

### PR DESCRIPTION
**Pull request by gnawux**
from the project root dir

Signed-off-by: Wang Xu <gnawux@gmail.com>

### CODE REVIEW

**Comment by Jimmy-Xu** [comment]
retest this please @hykins

**Comment by laijs** [comment]
The binary cmd/protoc-gen-gogo/protoc-gen-gogo doesn't need to be added and pushed.

**Comment by laijs** [comment]
I think it is better that protoc-gen-gogo is moved into hack/

**Comment by gnawux** [comment]
@laijs the reason I didn't move `protoc-gen-gogo` to `hack/` is -- I found in `kubernetes`'s repo, I found some auxiliary tools were placed in `cmd/` dir as well...

**Comment by gnawux** [comment]
@laijs updated, removed the binary files checked in by mistake, and update `.gitignore` to avoid checking in binary files.

**Pull request merged**
