### PR TITLE
Refactor hyperd daemon package

### PR DESCRIPTION
**Pull request by gnawux**
- move all the pod management procedures from runv to hyperd
- make the structures easier to maintain

//WIP, could not merge yet.

### CODE REVIEW

**Comment by gnawux** [comment]
Still have something to fix, including

- info
- build
- vbox graph driver (should we disable it now?)

and will rebase to current master after the fix

**Comment by gnawux** [comment]
All the major parts been done. now

- fix build
- rebase to current master
- test

**Comment by gnawux** [comment]
rebased to master ( #447 ), however, still lot of things to be fixed

**Comment by gnawux** [comment]
fixed the build, but still need to correct the behaviors.

**Comment by gnawux** [comment]
```
OOPS: 9 passed, 1 skipped, 8 FAILED
--- FAIL: Test (74.55s)
```

no panic at least, better than `0 passed`.

go on

**Comment by gnawux** [comment]
```OOPS: 11 passed, 1 skipped, 6 FAILED```

two more `passed`

**Comment by gnawux** [comment]
```OOPS: 13 passed, 1 skipped, 4 FAILED```

two more again.

**Comment by gnawux** [comment]
OOPS: 15 passed, 1 skipped, 2 FAILED

- [x] PASS: hyper_test.go:256: TestSuite.TestAddListDeleteService     24.350s
- [x] PASS: hyper_test.go:125: TestSuite.TestCreateAndStartPod        17.858s
- [x] PASS: hyper_test.go:168: TestSuite.TestCreateContainer  14.071s
- [x] PASS: hyper_test.go:56: TestSuite.TestGetContainerInfo  0.003s
- [x] PASS: hyper_test.go:44: TestSuite.TestGetContainerList  0.001s
- [x] PASS: hyper_test.go:70: TestSuite.TestGetContainerLogs  0.001s
- [x] PASS: hyper_test.go:50: TestSuite.TestGetImageList      0.002s
- [x] PASS: hyper_test.go:111: TestSuite.TestGetPodInfo       0.001s
- [x] PASS: hyper_test.go:32: TestSuite.TestGetPodList        0.000s
- [x] PASS: hyper_test.go:38: TestSuite.TestGetVMList 0.000s
- [x] PASS: hyper_test.go:417: TestSuite.TestPauseAndUnpausePod       7.729s
- [x] PASS: hyper_test.go:491: TestSuite.TestPing     0.000s
- [x] PASS: hyper_test.go:84: TestSuite.TestPostAttach        11.977s
- [x] PASS: hyper_test.go:222: TestSuite.TestPullImage        45.522s
- [ ] FAIL: hyper_test.go:191: TestSuite.TestRenameContainer
- [x] PASS: hyper_test.go:389: TestSuite.TestSetPodLabels     7.335s
- [ ] FAIL: hyper_test.go:357: TestSuite.TestStartAndStopPod

**Comment by gnawux** [comment]
rename container is fixed

- [x] PASS: hyper_test.go:256: TestSuite.TestAddListDeleteService     24.350s
- [x] PASS: hyper_test.go:125: TestSuite.TestCreateAndStartPod        17.858s
- [x] PASS: hyper_test.go:168: TestSuite.TestCreateContainer  14.071s
- [x] PASS: hyper_test.go:56: TestSuite.TestGetContainerInfo  0.003s
- [x] PASS: hyper_test.go:44: TestSuite.TestGetContainerList  0.001s
- [x] PASS: hyper_test.go:70: TestSuite.TestGetContainerLogs  0.001s
- [x] PASS: hyper_test.go:50: TestSuite.TestGetImageList      0.002s
- [x] PASS: hyper_test.go:111: TestSuite.TestGetPodInfo       0.001s
- [x] PASS: hyper_test.go:32: TestSuite.TestGetPodList        0.000s
- [x] PASS: hyper_test.go:38: TestSuite.TestGetVMList 0.000s
- [x] PASS: hyper_test.go:417: TestSuite.TestPauseAndUnpausePod       7.729s
- [x] PASS: hyper_test.go:491: TestSuite.TestPing     0.000s
- [x] PASS: hyper_test.go:84: TestSuite.TestPostAttach        11.977s
- [x] PASS: hyper_test.go:222: TestSuite.TestPullImage        45.522s
- [x] PASS: hyper_test.go:191: TestSuite.TestRenameContainer  14.601s
- [x] PASS: hyper_test.go:389: TestSuite.TestSetPodLabels     7.335s
- [ ] FAIL: hyper_test.go:357: TestSuite.TestStartAndStopPod

**Comment by xiaods** [comment]
Cool

**Comment by gnawux** [comment]
```OK: 17 passed, 1 skipped
--- PASS: Test (116.71s)
PASS
ok      github.com/hyperhq/hyperd/integration   116.720s```

There are still lots of issues to fix, however, at least the integration cases are passed. Cheers and go on.

**Comment by gnawux** [comment]
```The log length has exceeded the limit of 4 MB

The job has been terminated```

...

**Comment by gnawux** [comment]
```
+++ [1122 23:39:27] TEST PASSED
+++ [1122 23:39:27] Clean up complete
```

Passed one round, still need fix the save/re-load issues

**Comment by gnawux** [comment]
WOW! It is the first time this branch pass the test in the past 5 months. 

There are still lot of known issues to be solved, however, it has never been so close to be completed.

**Comment by gnawux** [comment]
Added save/load to/from leveldb

**Comment by gnawux** [comment]
Squashed the commits. Same contents with the previous commits. And the old commits are kept [here](https://github.com/gnawux/hyper/tree/refactor_bak).

**Comment by gnawux** [comment]
I listed remain tasks in #462 , and we may merge this and keep working on fix all issues.

**Comment by feiskyer** [comment]
Cool. LGTM.

**Pull request merged**
