### PR TITLE
use Vmlogd to log vm console log

### PR DESCRIPTION
**Pull request by gao-feng**
need https://github.com/hyperhq/runv/pull/456

### CODE REVIEW

**Comment by gao-feng** [comment]
retest this please, hykins

**Comment by gnawux** [comment]
@gao-feng sorry, I merged #597 and introduced conflict with this PR, could you update it again?

**Comment by gnawux** [comment]
```
/home/travis/gopath/src/github.com/hyperhq/hyperd/hack/lib/test.sh: line 33: test: too many arguments
!!! Error in /home/travis/gopath/src/github.com/hyperhq/hyperd/hack/lib/test.sh:33
  'test $res -eq 17' exited with status 2
```

**Comment by gao-feng** [comment]
hykins failed

```
mount nfs share 192.168.123.22:/export to /export, tmp path /tmp//export

executing cmd mount.nfs4 -n 192.168.123.22:/export /tmp//export

RPC: Registered named UNIX socket transport module.

RPC: Registered udp transport module.

RPC: Registered tcp transport module.

RPC: Registered tcp NFSv4.1 backchannel transport module.

Key type dns_resolver registered

NFS: Registering the id_resolver key type

Key type id_resolver registered

Key type id_legacy registered

INFO: rcu_sched detected stalls on CPUs/tasks:

	(detected by 0, t=218673 jiffies, g=531, c=530, q=6)

All QSes seen, last rcu_sched kthread activity 218673 (4294890128-4294671455), jiffies_till_next_fqs=3, root ->qsmask 0x0

kworker/0:0H    R  running task        0     5      2 0x00000008

Workqueue: xprtiod xs_tcp_setup_socket [sunrpc]

 ffff88000f603ec0 ffffffff81075bb2 ffff88000f618200 0000000000000000

 ffffffff8183e180 ffffffff8109be67 0000000000000000 0000000000000000

 0000000000000006 ffffffff8183e180 00745d1e000ccccd ffff88000e8f4c40

Call Trace:

 <IRQ>  [<ffffffff81075bb2>] ? sched_show_task+0xd2/0x140

 [<ffffffff8109be67>] ? rcu_check_callbacks+0x727/0x730

 [<ffffffff8109e1f3>] ? update_process_times+0x23/0x50

 [<ffffffff810abb13>] ? tick_sched_timer+0x33/0x60

 [<ffffffff8109e8e2>] ? __hrtimer_run_queues+0x92/0x100

 [<ffffffff8109edd4>] ? hrtimer_interrupt+0x94/0x170

 [<ffffffff81039aa4>] ? smp_apic_timer_interrupt+0x34/0x50

 [<ffffffff814e6b27>] ? apic_timer_interrupt+0x87/0x90

 <EOI>  [<ffffffff813dd40c>] ? __dev_queue_xmit+0x27c/0x5f0

 [<ffffffff813e4c7b>] ? neigh_probe+0x3b/0x50

 [<ffffffff813e4c7b>] ? neigh_probe+0x3b/0x50

 [<ffffffff813e6ab8>] ? __neigh_event_send+0x98/0x220

 [<ffffffff813e6da7>] ? neigh_resolve_output+0x117/0x1a0

 [<ffffffff81414c44>] ? ip_finish_output2+0x1a4/0x300

 [<ffffffff81416333>] ? ip_finish_output+0x83/0x1d0

 [<ffffffff81416e01>] ? ip_output+0xb1/0xc0

 [<ffffffff813c1c50>] ? __sk_dst_check+0x30/0x70

 [<ffffffff814165c2>] ? ip_local_out+0x12/0x40

 [<ffffffff8142d5a9>] ? tcp_transmit_skb+0x479/0x880

 [<ffffffff8142ee7d>] ? tcp_connect+0x5dd/0x810

 [<ffffffff813d1fb1>] ? secure_tcp_sequence_number+0x71/0xb0

 [<ffffffff81431f8a>] ? tcp_v4_connect+0x32a/0x460

 [<ffffffff81448beb>] ? __inet_stream_connect+0x8b/0x290

 [<ffffffff813c318b>] ? release_sock+0x3b/0x90

 [<ffffffff8141fd3b>] ? do_tcp_setsockopt.isra.43+0xfb/0x800

 [<ffffffff81448e1e>] ? inet_stream_connect+0x2e/0x50

 [<ffffffffa0006e80>] ? xs_tcp_setup_socket+0x70/0x3a0 [sunrpc]

 [<ffffffff8106739f>] ? process_one_work+0x12f/0x310

 [<ffffffff8106769d>] ? worker_thread+0x11d/0x490

 [<ffffffff81067580>] ? process_one_work+0x310/0x310

 [<ffffffff8106c4c9>] ? kthread+0xb9/0xd0

 [<ffffffff8106c410>] ? kthread_park+0x50/0x50

 [<ffffffff814e6165>] ? ret_from_fork+0x25/0x30

rcu_sched kthread starved for 218673 jiffies! g531 c530 f0x2 RCU_GP_WAIT_FQS(3) ->state=0x0

rcu_sched       R  running task        0     7      2 0x00000000

 ffff88000dbfa800 0000000000000000 ffff88000e8ce040 ffff88000f617500

 ffff88000e928c80 ffffc900000a3dc8 ffffffff814e2782 00000000fffb7c5e

 ffff88000e928c80 00000000fffb7c62 ffffc900000a3e00 ffff88000f60f780

Call Trace:

 [<ffffffff814e2782>] ? __schedule+0x192/0x530

 [<ffffffff814e2b51>] ? schedule+0x31/0x80

 [<ffffffff814e5051>] ? schedule_timeout+0x121/0x240

 [<ffffffff8109d6b0>] ? del_timer_sync+0x50/0x50

 [<ffffffff8109afe4>] ? rcu_gp_kthread+0x344/0x800

 [<ffffffff814e278a>] ? __schedule+0x19a/0x530

 [<ffffffff8109aca0>] ? force_qs_rnp+0x180/0x180

 [<ffffffff8106c4c9>] ? kthread+0xb9/0xd0

 [<ffffffff8106c410>] ? kthread_park+0x50/0x50

 [<ffffffff814e6165>] ? ret_from_fork+0x25/0x30

clocksource: timekeeping watchdog on CPU0: Marking clocksource 'tsc' as unstable because the skew is too large:

clocksource:                       'hpet' wd_now: 1a573bb1 wd_last: 18994f65 mask: ffffffff

clocksource:                       'tsc' cs_now: 153182c2744 cs_last: e2f03dbc17 mask: ffffffffffffffff

clocksource: Switched to clocksource hpet

mount.nfs4: Connection timed out

mount.nfs4 -n 192.168.123.22:/export /tmp//export cmd exit normally, status 32

cmd mount.nfs4 -n 192.168.123.22:/export /tmp//export exit unexpectedly, status 8192

container sets up voulme failed

hyper send container inited event: error

wait for setup container rootfs failed

create child process pid=345 in the sandbox

fail to enter container ns: Bad file descriptor

hyper send enter container ns event: error

hyper ctl append type 10, len 0
```

**Comment by bergwolf** [comment]
the nfs test failure is due to guest clocksource issue fixed by https://github.com/hyperhq/runv/pull/494. I'll update runv deps to include it.

**Comment by bergwolf** [comment]
retest this please, @hykins

**Pull request merged**
