### PR TITLE
update deb pkg to 0.7.0 and add service file and config file

### PR DESCRIPTION
**Pull request by xlgao-zju**
update deb pkg to 0.7.0. And add service file and config file in deb pkg.

Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>

### CODE REVIEW

**Comment by gnawux** [comment]
Good, Thank you @xlgao-zju . I used the following patch for 0.7.0 deb build, sorry for not posting in time, and could you just update your pr based on it?

```
diff --git a/package/dist/lib/systemd/system/hyperd.service b/package/dist/lib/systemd/system/hyperd.service                                                                                            [32/649]
index 3aac5ea..59f6410 100644
--- a/package/dist/lib/systemd/system/hyperd.service
+++ b/package/dist/lib/systemd/system/hyperd.service
@@ -1,6 +1,6 @@
 [Unit]
 Description=hyperd
-Documentation=http://docs.hyper.sh
+Documentation=http://docs.hypercontainer.io
 After=network.target
 Requires=

diff --git a/package/ubuntu/hypercontainer/debian/changelog b/package/ubuntu/hypercontainer/debian/changelog
index 70a0cdf..5a3f697 100644
--- a/package/ubuntu/hypercontainer/debian/changelog
+++ b/package/ubuntu/hypercontainer/debian/changelog
@@ -1,3 +1,13 @@
+hypercontainer (0.7.0-2) xenial; urgency=low
+
+  * add service and config file to package
+
+ -- Hyper Dev Team <dev@hyper.sh>  Sat, 30 Oct 2016 16:21:08 +0800
+hypercontainer (0.7.0-1) xenial; urgency=low
+
+  * Release 0.7.0
+
+ -- Hyper Dev Team <dev@hyper.sh>  Fri, 29 Oct 2016 22:30:08 +0800
 hypercontainer (0.6.2-1) xenial; urgency=low

   * Initial release
diff --git a/package/ubuntu/hypercontainer/debian/rules b/package/ubuntu/hypercontainer/debian/rules
index 97006e6..b4aed2f 100755
--- a/package/ubuntu/hypercontainer/debian/rules
+++ b/package/ubuntu/hypercontainer/debian/rules
@@ -25,6 +25,7 @@ override_dh_auto_install:
        mkdir -p debian/hypercontainer/usr/bin
        cp -aT hyperd debian/hypercontainer/usr/bin/hyperd
        cp -aT hyperctl debian/hypercontainer/usr/bin/hyperctl
+       cp -r package/dist/* debian/hypercontainer/

 override_dh_auto_clean:
        rm -rf go hyperd hyperctl
diff --git a/package/ubuntu/hypercontainer/make-hypercontainer-deb.sh b/package/ubuntu/hypercontainer/make-hypercontainer-deb.sh
index 1215748..1d855d6 100755
--- a/package/ubuntu/hypercontainer/make-hypercontainer-deb.sh
+++ b/package/ubuntu/hypercontainer/make-hypercontainer-deb.sh
@@ -9,7 +9,7 @@ if [ $# -gt 0 ] ; then
 fi

 # install addtional pkgs in order to build deb pkg
-sudo apt-get install -y autoconf automake pkg-config libdevmapper-dev libsqlite3-dev libvirt-dev libxen-dev uuid-dev golang xen-hypervisor-4.6-amd64 -qq
+sudo apt-get install -y autoconf automake pkg-config libdevmapper-dev libsqlite3-dev libvirt-dev libxen-dev uuid-dev golang xen-system-amd64 -qq

 # get hyperd tar ball
 cd $PROJECT
diff --git a/package/ubuntu/hyperstart/debian/changelog b/package/ubuntu/hyperstart/debian/changelog
index 2de9466..6adc846 100644
--- a/package/ubuntu/hyperstart/debian/changelog
+++ b/package/ubuntu/hyperstart/debian/changelog
@@ -1,3 +1,8 @@
+hyperstart (0.7.0-1) xenial; urgency=low
+
+  * Release 0.7.0
+
+ -- Hyper Dev Team <dev@hyper.sh>  Fri, 29 Oct 2016 22:30:08 +0800
 hyperstart (0.6.2-1) xenial; urgency=low

   * Initial release
diff --git a/package/ubuntu/make-deb.sh b/package/ubuntu/make-deb.sh
index 37253fe..d42d7ea 100755
--- a/package/ubuntu/make-deb.sh
+++ b/package/ubuntu/make-deb.sh
@@ -3,6 +3,6 @@
 PROJECT=$(readlink -f $(dirname $0)/../..)
 UBUNTU_DIR=${PROJECT}/package/ubuntu

-${UBUNTU_DIR}/hypercontainer/make-hypercontainer-deb.sh
-${UBUNTU_DIR}/hyperstart/make-hyperstart-deb.sh
+${UBUNTU_DIR}/hypercontainer/make-hypercontainer-deb.sh "$@"
+${UBUNTU_DIR}/hyperstart/make-hyperstart-deb.sh "$@"
```

**Comment by xlgao-zju** [comment]
@gnawux will do.

**Comment by xlgao-zju** [comment]
@gnawux updated.

**Comment by gnawux** [comment]
@xlgao-zju thank you very much

**Pull request merged**
