### PR TITLE
pod level port-mapping support

### PR DESCRIPTION
**Pull request by gnawux**
This PR is to implement pod-level port-mapping ( #382 ), which include

- [x] portmapping as a pod level object in pod spec
- [x] API and command line for port mapping operation
- [x] port mapping operation in pod life cycle management routines
- [x] move iptables code from runv back to hyperd
- [x] range port mapping

### CODE REVIEW

**Comment by gnawux** [comment]
Almost done, will do test/fix and add more unit test cases

**Comment by gnawux** [comment]
Functional test finished, usage:

## Port Mapping configuration in Pod Level

```json
{
  "portmappings": [{
    "containerport": "80",
    "hostport": "3000",
    "protocol": "tcp",
  },{
    "containerport": "8000-8080",
    "hostport": "3000-3080",
    "protocol": "tcp",
  }]
}
```

## Publish port from command line

```
hyperd@[Go:(Workspace)]➜ sudo ./hyperctl run -t --rm --publish 3000:1300 busybox:latest /bin/sh
/ # nc -l -p 1300
aaa
/ # exit
```

#### correspond request from outside

```
# nc 192.168.142.136 3000 <<END
aaa
END
```

## Publish port range

```
hyperd@[Go:(Workspace)]➜ time sudo ./hyperctl run -t --rm --publish 3000-3100:1300-1400 busybox:latest /bin/sh
/ # nc -l -p 1300
aaa
/ # exit
```

## Dynamically change portmapping with `hyperctl ports subcommands`

```
hyperd@[Go:(Workspace)]➜  sudo ./hyperctl ports add -p 3000:1300  busybox-latest-4488498752
hyperd@[Go:(Workspace)]➜  sudo ./hyperctl ports ls  busybox-latest-4488498752
Protocol            Host Ports          Container Ports
tcp                 3000                1300
hyperd@[Go:(Workspace)]➜  sudo ./hyperctl ports delete -p 3000:1300  busybox-latest-4488498752
hyperd@[Go:(Workspace)]➜  sudo ./hyperctl ports ls  busybox-latest-4488498752
Protocol            Host Ports          Container Ports
hyperd@[Go:(Workspace)]➜ 
```

**Comment by gnawux** [comment]
added an example pod for podmapping:

`examples/port-mapping.pod`:

```json
{
        "id": "port-mapping-test",
        "containers" : [{
            "name": "pmtest",
            "image": "busybox:latest",
			"command": ["/bin/nc", "-l", "-p", "1300"]
        }],
        "resource": {
            "vcpu": 1,
            "memory": 128
        },
        "portmappings": [{
			"containerport": "1300-1310",
			"hostport": "3000-3010",
			"protocol": "tcp"
		}]
}
```

**Comment by gnawux** [comment]
ready for review @bergwolf

**Comment by gnawux** [comment]
the new commit re-enable the in sandbox portmapping for hypernetes, controlled by (same as before):

1. `disableIptables` configuration entry in config file
2. `portmappingWhiteLists` fields in pod spec

An example pod proviede in `hyperd/examples/port-mapping-in-sandbox.pod`. 

Note: the *"in sandbox portmapping"* doesn't do NAT in hyperd, it should be completed by other components. i.e. during test of this feature, you should access the ip address of the container instead of the host's.

**Comment by bergwolf** [comment]
LGTM!

**Pull request merged**
