### PR TITLE
Remove auxiliary container support

### PR DESCRIPTION
**Pull request by Crazykev**
Since ipvs based service have been merged, we don't need this anymore. 

/cc @feiskyer 

Signed-off-by: Crazykev <crazykev@zju.edu.cn>

### CODE REVIEW

**Comment by gnawux** [comment]
Will we have other assistant container, such as those for the pod initialization? Or will they be treat as normal container?

**Comment by Crazykev** [comment]
I only find two types of container for now, service container and regular container. Hyperstart-exec container is a virtual container in hyperstart, won't affect this. I'm not sure others.

**Comment by gnawux** [comment]
@feiskyer @resouer could you confirm that we (hyperd) don't need any type of assistant containers in recent months?

**Comment by feiskyer** [comment]
@gnawux Yes, we don't need it any more.

**Comment by feiskyer** [comment]
LGTM

**Pull request merged**
