### PR TITLE
fix incorrect nic name

### PR DESCRIPTION
**Pull request by gao-feng**
Signed-off-by: Gao feng <omarapazanadi@gmail.com>

### CODE REVIEW

**Comment by gao-feng** [comment]
@bergwolf 
Hykins failed due to mount nfs failed, could you please check this? Thanks!

```
I0713 07:29:48.689520   10258 vm_console.go:96] SB[vm-gjFVAQMaPR] [CNL] hyper_modify_event modify event fd 3, 0x61e688, event 8193
I0713 07:29:49.259477   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] mount.nfs4: rpc.statd is not running but is required for remote locking.
I0713 07:29:49.262624   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] mount.nfs4: Either use '-o nolock' to keep locks local, or start statd.
I0713 07:29:49.277648   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] mount.nfs4 -n 192.168.123.22:/export /tmp//export cmd exit normally, status 32
I0713 07:29:49.281505   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] cmd mount.nfs4 -n 192.168.123.22:/export /tmp//export exit unexpectedly, status 8192
I0713 07:29:49.285639   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] container sets up voulme failed
I0713 07:29:49.287730   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] hyper send container inited event: error
I0713 07:29:49.289419   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] wait for setup container rootfs failed
I0713 07:29:49.303818   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] create child process pid=609 in the sandbox
I0713 07:29:49.314948   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] fail to enter container ns: Bad file descriptor
I0713 07:29:49.315820   10258 vm_console.go:96] SB[vm-lOdpSnxhru] [CNL] hyper send enter container ns event: error
```

**Comment by feiskyer** [comment]
The code LGTM.

**Comment by bergwolf** [comment]
The `hyeprhq/nfs-server-tester` container failed to start as its hyperstart got HUP event after executing the first exec command. Then the nfs client container failed to connect to the nfs server.
```
07:29:29 I0713 07:29:30.440442   10258 vm_console.go:96] SB[vm-gjFVAQMaPR] [CNL] hyper_handle_event event EPOLLHUP or EPOLLERR, he 0x1721f48, fd 12, 10
```

It does not seem like hyperd closed the connection. There might be something wrong in exec cleanup code.

**Comment by bergwolf** [comment]
Let's track the CI failure at https://github.com/hyperhq/hyperstart/issues/317

**Comment by bergwolf** [comment]
retest this please, @hykins

**Comment by bergwolf** [comment]
hykins is running too slow and timed out. Maybe we should raise the time limit?

**Comment by bergwolf** [comment]
retest this please, @hykins

**Pull request merged**
