### PR TITLE
travis-ci: use hyperhq/qemu 2.4.1-template

### PR DESCRIPTION
**Pull request by bergwolf**
It seems the one from ubuntu image has issue with serial port
connection.

### CODE REVIEW

**Comment by bergwolf** [comment]
travis failed due to network issue:
`Error trying v2 registry: Get https://gcr.io/v2/google_containers/k8s-dns-sidecar-amd64/blobs/sha256:fc5e302d8309a8deb3315452b428969aed4aa931189b10a3231ce48fc0687224: dial tcp 74.125.132.82:443: i/o timeout `

**Comment by laijs** [comment]
retest this please, @hykins

**Comment by bergwolf** [comment]
retest this please, @hykins

**Comment by gao-feng** [comment]
seems still has the serial port broken problem in this pr?(hykins faild http://ci.hypercontainer.io:8080/job/hyperd-auto/371/console)

```
01:25:42 I0422 01:25:41.793208    8892 vm_console.go:96] SB[vm-iYjTNjuyPE] [CNL] ACPI: PCI Interrupt Link [LNKB] enabled at IRQ 10
01:25:42 I0422 01:25:41.797414    8892 vm_console.go:96] SB[vm-iYjTNjuyPE] [CNL] virtio-pci 0000:00:02.0: virtio_pci: leaving for legacy driver
01:25:42 I0422 01:25:42.172757    8892 vm_console.go:96] SB[vm-iYjTNjuyPE] [CNL] ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 11
01:25:42 I0422 01:25:42.172929    8892 vm_console.go:96] SB[vm-iYjTNjuyPE] [CNL] virtio-pci 0000:00:03.0: virtio_pci: leaving for legacy driver
01:25:43 I0422 01:25:42.522286    8892 vm_console.go:96] SB[vm-iYjTNjuyPE] [CNL] ACPI: PCI Interrupt Link [LNKD] enabled at IRQ 11
01:25:43 I0422 01:25:42.526319    8892 vm_console.go:96] SB[vm-iYjTNjuyPE] [CNL] virtio-pci 0000:00:04.0: virtio_pci: leaving for legacy driver
01:25:43 I0422 01:25:42.888697    8892 vm_console.go:96] SB[vm-iYjTNjuyPE] [CNL] ACPI: PCI Interrupt Link [LNKA] enabled at IRQ 10
01:25:43 I0422 01:25:42.893060    8892 vm_console.go:96] SB[vm-iYjTNjuyPE] [CNL] virtio-pci 0000:00:05.0: virtio_pci: leaving for legacy driver
01:25:43 E0422 01:25:42.907218    8892 json.go:370] read tty data failed
01:25:43 E0422 01:25:42.907241    8892 json.go:427] SB[vm-iYjTNjuyPE] tty socket closed, quit the reading goroutine: EOF
01:25:43 I0422 01:25:42.907247    8892 json.go:89] SB[vm-iYjTNjuyPE] close jsonBasedHyperstart
01:25:43 E0422 01:25:42.907271    8892 json.go:570] SB[vm-iYjTNjuyPE] get hyperstart API version error: hyperstart closed
01:25:43 W0422 01:25:42.907280    8892 hypervisor.go:47] SB[vm-iYjTNjuyPE] keep-alive test end with error: hyperstart closed
01:25:43 I0422 01:25:42.907309    8892 hypervisor.go:23] SB[vm-iYjTNjuyPE] main event loop got message 14(ERROR_INIT_FAIL)
01:25:43 E0422 01:25:42.907317    8892 vm_states.go:285] SB[vm-iYjTNjuyPE] hyperstart failed: hyperstart closed
01:25:43 E0422 01:25:42.907326    8892 vm_states.go:243] SB[vm-iYjTNjuyPE] Shutting down because of an exception: %!(EXTRA string=connection to vm broken)
01:25:43 I0422 01:25:42.907331    8892 vm_states.go:246] SB[vm-iYjTNjuyPE] poweroff vm based on command: connection to vm broken
01:25:43 I0422 01:25:42.907405    8892 json.go:395] SB[vm-iYjTNjuyPE] tty chan closed, quit sent goroutine
01:25:43 E0422 01:25:42.907435    8892 vm_states.go:223] SB[vm-iYjTNjuyPE] Start POD failed: hyperstart closed
01:25:43 E0422 01:25:42.907468    8892 run.go:38] test-remove-container-with-volume: failed to add pod: hyperstart closed
01:25:43 E0422 01:25:42.907495    8892 server.go:170] Handler for POST /v0.8.0/pod/create returned error: hyperstart closed
```

**Comment by bergwolf** [comment]
hykins is still using the upstream qemu binary. @Jimmy-Xu is helping to change it.

**Comment by bergwolf** [comment]
retest this please, @hykins

**Comment by bergwolf** [comment]
retest this please, @hykins

**Comment by bergwolf** [comment]
retest this please, @hykins

**Comment by bergwolf** [comment]
retest this please, @hykins

**Comment by gnawux** [comment]
retest this please, hykins

**Comment by gnawux** [comment]
retest this please, hykins

**Comment by gnawux** [comment]
LGTM

**Pull request merged**
