### PR TITLE
do not attach stderr log stream for container without tty

### PR DESCRIPTION
**Pull request by gnawux**
I test about 300 pods like this

```
sudo ./hyperctl run --rm -t --name "hello${i}"  busybox sh -c 'echo hello'
```

And about 4% of them lost their output because stderr closed earlier than stdin.

Signed-off-by: Wang Xu <gnawux@gmail.com>

### CODE REVIEW

**Comment by gnawux** [comment]
further test shows this could not solve the issue yet.

**Comment by gnawux** [comment]
img_4285

The issue is -- container stop will lead to streams breaking at once, and message will be lost if they have not been sent to the client.

**Comment by gnawux** [comment]
@laijs  do you have any suggestion?

**Comment by Crazykev** [comment]
This reminds another similar random test failure in frakti, which randomly missing stderr output. 
I tried with
```
sudo ./hyperctl run --rm --name "hello${i}"  busybox blabla
```
There is a chance that stderr output `exec failed: No such file or directory` is missing. Is it also related with this?
/cc @feiskyer

**Comment by laijs** [comment]
LGTM. I'm going to merge it. could you create new issues if there any problem unsolved. @gnawux @Crazykev

**Comment by gnawux** [comment]
@laijs Agree. This PR does a correct job, but does not solved the issue. I will file a new one and discuss with you.

**Pull request merged**
