### PR TITLE
make ci runnable with forked repos

### PR DESCRIPTION
**Pull request by bergwolf**
Add `go_import_path` to import hyperhq/hyperd.

### CODE REVIEW

**Comment by laijs** [comment]
How about https://docs.travis-ci.com/user/languages/go/#Go-Import-Path

**Comment by bergwolf** [comment]
ah, `go_import_path` should be the official way of doing the same thing. Thanks for pointing it out!

**Comment by bergwolf** [comment]
updated to use `go_import_path` instead.

**Comment by Jimmy-Xu** [comment]
test this please @hykins

**Pull request merged**
