### PR TITLE
Restart attach

### PR DESCRIPTION
**Pull request by gnawux**
adjust stream setup for the case container restart

for #539.

need update godep after hyperhq/runv#469 merged. Do not merge yet.

### CODE REVIEW

**Comment by gnawux** [comment]
updated this PR as #605 has been merged and runv vendor has been updated.

**Comment by gnawux** [comment]
Test result:

```
➜ sudo ./hyperctl list container
Container ID                                                       Name                 POD ID               Status
2c8abf13b126d71e8fdfdf21d117633178f6f2635f4d884f3179c3e7e306a54c   busybox-9326359365   busybox-9326359365   succeeded
➜ sudo ./hyperctl start -c busybox-9326359365
Successfully started container busybox-9326359365
➜ sudo ./hyperctl attach busybox-9326359365

/ # ls
bin   dev   etc   home  lib   proc  root  sys   tmp   usr   var
/ # exit
➜
```

**Comment by gnawux** [comment]
@laijs & @Crazykev please take a look, this should fix #539

**Comment by gnawux** [comment]
retest this please hykins

**Comment by gnawux** [comment]
retest this please hykins

**Comment by Crazykev** [comment]
Seems there is some issue in hyperstart, I couldn't start a container(after exit a attach).
```
I0418 10:48:42.098217    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] recreate file ./etc/hosts
I0418 10:48:42.098842    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] recreate file ./etc/hostname
I0418 10:48:42.099333    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] recreate symlink ./etc/mtab to /proc/mounts
I0418 10:48:42.099813    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] container sets up init layer failed
I0418 10:48:42.100067    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] hyper send container inited event: error
I0418 10:48:42.100319    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] wait for setup container rootfs failed
I0418 10:48:42.100762    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] create child process pid=341 in the sandbox
I0418 10:48:42.101124    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] fail to enter container ns: Bad file descriptor
I0418 10:48:42.101383    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] hyper send enter container ns event: error
I0418 10:48:42.101603    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] hyper ctl append type 10, len 0
I0418 10:48:42.101980    6683 vm_console.go:96] SB[vm-DPkMJaTycz] [CNL] hyper_handle_event event EPOLLOUT, he 0x61d648, fd 3, 0x61d4c0
```

**Comment by gnawux** [comment]
@Crazykev woo.... my test was not on the latest hyperstart

**Comment by gnawux** [comment]
@Crazykev confirm this issue, hyperhq/hyperstart#290 looks doesn't work, while  hyperhq/hyperstart#287 works

**Comment by Crazykev** [comment]
@gnawux tried with hyperhq/hyperstart#287 and works for me.

**Comment by laijs** [comment]
LGTM

**Pull request merged**
