### PR TITLE
post image/load ,post /auth

### PR DESCRIPTION
**Pull request by heartlock**
Signed-off-by: heartlock 21521209@zju.edu.cn

### CODE REVIEW

**Comment by resouer** [comment]
@heartlock You should add [integration test](https://github.com/hyperhq/hyperd/blob/master/integration/hyper_test.go)to self-prove your code. A good example to follow is: https://github.com/hyperhq/hyperd/pull/349

**Comment by heartlock** [comment]
@resouer I add integration test ,but still check fail

**Comment by Jimmy-Xu** [comment]
Can one of the admins verify this patch?

**Comment by Jimmy-Xu** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
