### PR TITLE
Fixed bug: http service cannot work

### PR DESCRIPTION
**Pull request by vitan**

### CODE REVIEW

**Comment by vitan** [comment]
@gnawux  @laijs  have a look please. I am not sure why My PR triggering other unittest failed

**Comment by gnawux** [comment]
looks failed on unix socket

```
hyperctl ERROR: An error occurred trying to connect: Get http:///var/run/hyper.sock/info: http: no Host in request URL
!!! Error in hack/test-cmd.sh:135
  'sudo env PATH=$PATH hyperctl info' exited with status 255
```

**Comment by vitan** [comment]
wip: trigger the unittest for debug

**Comment by gnawux** [comment]
looks good

**Comment by gnawux** [comment]
I checked the server code, and do not find anything wrong with the url path. @vitan could you show me the error again? I am managing to eliminate the error.

**Comment by Jimmy-Xu** [comment]
Can one of the admins verify this patch?

**Comment by Jimmy-Xu** [comment]
Can one of the admins verify this patch?

**Comment by gnawux** [comment]
Can not reproduce this issue, and looks the patch may not fix

**Pull request closed without merging**
