### PR TITLE
Release v1.0

### PR DESCRIPTION
**Pull request by gnawux**
bump version and update packaging files

### CODE REVIEW

**Comment by gnawux** [comment]
- depends on #657 
- docs updates and release notes in hyperhq/docs.hypercontainer.io#27

**Comment by minz1027** [comment]
@gnawux Hi Xu, do you have a date when this will be merged?

**Comment by antoineherzog** [comment]
yeah, it would be very helpful! ?
also it would be very helpful to have a tutorial to install hyper in Ubuntu with packet.net
It fell very complicated right now.

**Comment by antoineherzog** [comment]
@gnawux

**Comment by gnawux** [comment]
@minz1027 @antoineherzog sorry folks, I have had to stay in hospital for a week accidentally in the past 7 days, and now, let's do it.

**Pull request merged**
